import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { Providers } from './providers/Providers'
import { ThemeProvider } from './providers/ThemeProvider'
import { Header } from '@/components/organisms/Header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <Providers>
          <ThemeProvider>
            <Header />
            <div className='flex flex-col min-h-screen py-8 items-center font-mono'>{children}</div>
             <footer className="text-xs text-muted py-6 text-center">
              © 2025 A2Z Blocks — Humbly built.
            </footer>
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  )
}
